//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dimensions.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("spec,表侧")]
        public string SpecSheetKeys {
            get {
                return ((string)(this["SpecSheetKeys"]));
            }
            set {
                this["SpecSheetKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("header,topbreak,banner,表头")]
        public string HeaderSheetKeys {
            get {
                return ((string)(this["HeaderSheetKeys"]));
            }
            set {
                this["HeaderSheetKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("increase,enhance,improve,raise,heighten,增加,提高,首选,非常相符,非常了解,唯一考虑,首先考虑,唯一,第一选择,第一")]
        public string HighFactorKeys {
            get {
                return ((string)(this["HighFactorKeys"]));
            }
            set {
                this["HighFactorKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net,nets")]
        public string NetKeys {
            get {
                return ((string)(this["NetKeys"]));
            }
            set {
                this["NetKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t2b,top2,t3b,top3,b2b,bottom2,b3b,bottom3,nps,topbox,tb")]
        public string TopBottomKeys {
            get {
                return ((string)(this["TopBottomKeys"]));
            }
            set {
                this["TopBottomKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("average,平均提及,均值,mean")]
        public string AverageKeys {
            get {
                return ((string)(this["AverageKeys"]));
            }
            set {
                this["AverageKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoRemoveHeaderType {
            get {
                return ((bool)(this["AutoRemoveHeaderType"]));
            }
            set {
                this["AutoRemoveHeaderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HeaderRowCount {
            get {
                return ((int)(this["HeaderRowCount"]));
            }
            set {
                this["HeaderRowCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddSubGroup {
            get {
                return ((bool)(this["AddSubGroup"]));
            }
            set {
                this["AddSubGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QueryShowValue {
            get {
                return ((bool)(this["QueryShowValue"]));
            }
            set {
                this["QueryShowValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("名字,name")]
        public string FixedLabelKeys {
            get {
                return ((string)(this["FixedLabelKeys"]));
            }
            set {
                this["FixedLabelKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("题号,question")]
        public string FixedNameKeys {
            get {
                return ((string)(this["FixedNameKeys"]));
            }
            set {
                this["FixedNameKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("基数,base")]
        public string FixedBaseKeys {
            get {
                return ((string)(this["FixedBaseKeys"]));
            }
            set {
                this["FixedBaseKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("top/bottom,top,bottom")]
        public string FixedTopBottomKeys {
            get {
                return ((string)(this["FixedTopBottomKeys"]));
            }
            set {
                this["FixedTopBottomKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mean/std,mean,std")]
        public string FixedMeanKeys {
            get {
                return ((string)(this["FixedMeanKeys"]));
            }
            set {
                this["FixedMeanKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("note,remark")]
        public string FixedRemarkKeys {
            get {
                return ((string)(this["FixedRemarkKeys"]));
            }
            set {
                this["FixedRemarkKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("summary")]
        public string FixedSummaryKeys {
            get {
                return ((string)(this["FixedSummaryKeys"]));
            }
            set {
                this["FixedSummaryKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("value,赋值")]
        public string FixedValueKeys {
            get {
                return ((string)(this["FixedValueKeys"]));
            }
            set {
                this["FixedValueKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("average,平均提及")]
        public string FixedAverageKeys {
            get {
                return ((string)(this["FixedAverageKeys"]));
            }
            set {
                this["FixedAverageKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadWithFixedHeaderType {
            get {
                return ((bool)(this["LoadWithFixedHeaderType"]));
            }
            set {
                this["LoadWithFixedHeaderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HorizenHeader {
            get {
                return ((bool)(this["HorizenHeader"]));
            }
            set {
                this["HorizenHeader"] = value;
            }
        }
    }
}
